### ISSUE TITLE
Query and query-frontend can't be scaled up

### ISSUE THREAD

**Issue by craigfurman** [banzaicloud/thanos-operator#69]
**Describe the bug**

The stateless components query and query-frontend have hard-coded replica counts, that can't be overriden in deploymentOverrides.

**Steps to reproduce the issue:**

Create a Thanos instance with `spec.queryFrontend.deploymentOverrides.replicas` to 2, and observe that the resultant deployment created by the operator has only one replica.

You can see the hardcoding here: https://github.com/craigfurman/thanos-operator/blob/query-frontend-service-type-configurability/pkg/resources/query_frontend/deployment.go#L40

**Expected behavior**

Query or QueryFrontend deployments have replica counts equal to the value of the relevant deploymentOverrides.replicas.

**Screenshots**

**Additional context**

**Comment by craigfurman** [comment]
I'm happy to send a PR for this, but I'm interested in feedback on another PR of mine first (https://github.com/banzaicloud/thanos-operator/pull/67), because that one also introduces a defaulted field and I want to be sure I'm on the right track with code generation and documentation first.

**Comment by bshifter** [comment]
We haven't tag the master branch since the fix, so the image is outdated probably. The code you forked already contains the fix, the hard-coded replicas value isn't problem anymore, it's more likely a default value. The `deployment.Spec = queryFrontend.DeploymentOverrides.Override(` line is where the magic happens: the override method rewrites the replicas field with the given value.

**Comment by craigfurman** [comment]
You're totally right @bshifter, and I see you've even tagged v0.1.2 which incorporates this fix as well. Thanks!
